[build]
  functions = "functions"

  [[redirects]]
  from = "/sasa"
  to ="/sasa"
  force = true
  status = 200
  conditions = {Role = ["registered"]}

[[redirects]]
  from = "/sasa"
  to = "/login"
  force = true
  status = 401

 



  

 